logging:
  level:
   root: debug
  path: /tmp/log.log

spring:
    datasource:
      url: jdbc:mysql://localhost:3309/coin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: admin
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        use-new-id-generator-mappings: false
      show-sql: true

socks5:
    host: localhost
    port: 1080
    enabled: true