logging:
  level:
   root: debug
  path: /tmp/log.log

spring:
    datasource:
      url: jdbc:mysql://192.168.30.135:3309/coin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: admin
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        use-new-id-generator-mappings: false
      show-sql: true

socks5:
    host: 127.0.0.1
    port: 1080
    enabled: true


websocket:
    debug: true
    host: wss://api.huobipro.com/ws

server:
  port: 5060
